services:
  web_server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web_server
    ports:
      - "${WEB_SERVER_HTTP_BIND_PORT}:${WEB_SERVER_HTTP_LISTEN_PORT}"
    environment:
      - HTTP_LISTEN_HOST=${WEB_SERVER_HTTP_LISTEN_HOST}
      - HTTP_LISTEN_PORT=${WEB_SERVER_HTTP_LISTEN_PORT}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://${WEB_SERVER_HTTP_LISTEN_HOST}:${WEB_SERVER_HTTP_LISTEN_PORT}/debug/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
